export const ACTION_PREFIX = 'HOME';

/**
 | ---------------------------------------------------------------------
 | ACTION TYPES | TEST
 | ---------------------------------------------------------------------
 | Define all your actionType constants here.
 |
 */

export const actionTypes = {
  FETCH_ACTION_MOVIES_REQUEST: 'FETCH_ACTION_MOVIES_REQUEST',
  FETCH_ACTION_MOVIES_SUCCESS: 'FETCH_ACTION_MOVIES_SUCCESS',
  FETCH_ACTION_MOVIES_FAILURE: 'FETCH_ACTION_MOVIES_FAILURE',
  FETCH_ROMANCE_MOVIES_REQUEST: 'FETCH_ROMANCE_MOVIES_REQUEST',
  FETCH_ROMANCE_MOVIES_SUCCESS: 'FETCH_ROMANCE_MOVIES_SUCCESS',
  FETCH_ROMANCE_MOVIES_FAILURE: 'FETCH_ROMANCE_MOVIES_FAILURE',
  FETCH_HORROR_MOVIES_REQUEST: 'FETCH_HORROR_MOVIES_REQUEST',
  FETCH_HORROR_MOVIES_SUCCESS: 'FETCH_HORROR_MOVIES_SUCCESS',
  FETCH_HORROR_MOVIES_FAILURE: 'FETCH_HORROR_MOVIES_FAILURE',
  FETCH_TRENDING_MOVIES_REQUEST: 'FETCH_TRENDING_MOVIES_REQUEST',
  FETCH_TRENDING_MOVIES_SUCCESS: 'FETCH_TRENDING_MOVIES_SUCCESS',
  FETCH_TRENDING_MOVIES_FAILURE: 'FETCH_TRENDING_MOVIES_FAILURE',
  FETCH_GENRE_LIST_REQUEST: 'FETCH_GENRE_LIST_REQUEST',
  FETCH_GENRE_LIST_SUCCESS: 'FETCH_GENRE_LIST_SUCCESS',
  FETCH_GENRE_LIST_FAILURE: 'FETCH_GENRE_LIST_FAILURE',
  FETCH_MOVIE_BY_GENRE_ID_REQUEST: 'FETCH_MOVIE_BY_GENRE_ID_REQUEST',
  FETCH_MOVIE_BY_GENRE_ID_SUCCESS: 'FETCH_MOVIE_BY_GENRE_ID_SUCCESS',
  FETCH_MOVIE_BY_GENRE_ID_FAILURE: 'FETCH_MOVIE_BY_GENRE_ID_FAILURE',
  FETCH_MOVIE_TRAILER_URL_REQUEST: 'FETCH_MOVIE_TRAILER_URL_REQUEST',
  FETCH_MOVIE_TRAILER_URL_SUCCESS: 'FETCH_MOVIE_TRAILER_URL_SUCCESS',
  FETCH_MOVIE_TRAILER_URL_FAILURE: 'FETCH_MOVIE_TRAILER_URL_FAILURE',
};
